import Head from "next/head";
import { Inter } from "@next/font/google";
import io from "socket.io-client";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

let socket;

export default function Home() {
    useEffect(() => {
        socketInitialization();
    }, []);

    const socketInitialization = async () => {
        await fetch("/api/socket");

        socket = io();

        socket.on("connect", () => {
            console.log("Connected!");
        });
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main></main>
        </>
    );
}
